### ISSUE TITLE
BUG(?): "Show .1 units" option does not apply to "Total Raid DPS"

### ISSUE THREAD

**Issue by AkiyoAratemuso** [hibiyasleep/ikegami#11]
![image](https://user-images.githubusercontent.com/42167298/51423543-e6d5f180-1bfc-11e9-922f-cacaf3015e0d.png)

Not sure if intended, but "Show .1 units" option does not hide decimal points in total raid DPS.

**Comment by hibiyasleep** [comment]
Yep that's a bug, ill fix it.
