### ISSUE TITLE
SUGGESTION: Pad decimal points with leading zeros in total raid DPS column

### ISSUE THREAD

**Issue by AkiyoAratemuso** [hibiyasleep/ikegami#12]
The columns are unnecessary "jumpy" due to decimal points are not padded, causing elements to move every refresh.

e.g total raid DPS column keep adjusting width every refresh due to raid DPS number going between 
28000, 
28128.2, 
28227.15

Note: Per-job/character DPS seems to be padded properly with numbers like 5018.0 showing up, so the issue is probably limited to total raid DPS only.

**Comment by hibiyasleep** [comment]
✔️ will be fixed in next release (very soon)

**Comment by hibiyasleep** [comment]
fixed in v0.1.9, decimal points are just hidden since it's not that important at my sight.
