### ISSUE TITLE
"Criticals" values mislabeled

### ISSUE THREAD

**Issue by mkolopanis** [hibiyasleep/ikegami#13]
Between this overlay and the kagerou, there is a mislabeling of which hits count as direct or criticals. In the attached image, this overlay counts D/!/!!! ast 211/186/61 but kagerou has 186/211/61 in the direct/crit/!!! category. 
![image](https://user-images.githubusercontent.com/8646829/55688507-122fc900-592e-11e9-853d-baad603e1b33.png)

**Comment by hibiyasleep** [comment]
oh i'm also confused about aligning those values. thanks!

**Comment by hibiyasleep** [comment]
Fixed in v0.1.9.
