### ISSUE TITLE
[Suggestion] Shortening number to K-thousands

### ISSUE THREAD

**Issue by Hoshiyuu** [hibiyasleep/ikegami#16]
With the release of Shadowbringers and number significance is now in the hundreds, can there be an option to display number in 12.34k or 12.3k as an option? Its a much more meaningful number now that DPS has bloated to 5 digits.

Perhaps an option for it to revert back to full numbers when the lowest DPS on display is less than 999?

Thank you!

**Comment by hibiyasleep** [comment]
I'm preparing it, in meantime I recommend to uncheck 'Show .1 values' then DPS should fit in 5 digits.

**Comment by Hoshiyuu** [comment]
Will do, been using that option since day one and it's very very helpful,
thanks!

**Comment by hibiyasleep** [comment]
Closed by 87e6934db6428b1873c1609beca2e5829bc666ca, sorry for late ;-;
