### ISSUE TITLE
[ERROR] url not responsed

### ISSUE THREAD

**Issue by kyan001** [hibiyasleep/ikegami#20]
http://kagerou.hibiya.moe/ikegami-test
I cannot visit this url now.

**Comment by rucellex** [comment]
Yes the url is not working and the Ikegami parse is not working.

**Comment by kyan001** [comment]
> 
> 
> Yes the url is not working and the Ikegami parse is not working.

You can run it on your server if you have one, or run it locally.

```sh
# install nvm: https://github.com/nvm-sh/nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

# install npm
nvm install node

# download this repo to some folder, for example /path/to/ikegami/
cd /path/to/ikegami
npm install  # install packages
npm run dev  # run, using `Ctrl + C` to stop.
```
Then put "http://localhost:9000" as your template location.

**Comment by kyan001** [comment]
http://kagerou.hibiya.moe/ikegami-test/ has back online, so I guess I should close this issue.
