### ISSUE TITLE
Settings cut off when first set up.

### ISSUE THREAD

**Issue by wxhl777** [hibiyasleep/ikegami#21]
The triple dot settings is not available when creating a new overlay with Ikegami. I had to switch to a different overlay, reize the window to be bigger and then switch back to ikegami in order to access the menu.

![image](https://user-images.githubusercontent.com/65934512/82856831-7e1a2a00-9f52-11ea-8db7-bce6c0078957.png)

**Comment by hibiyasleep** [comment]
I'll try to fix asap, thanks for reporting!
