### ISSUE TITLE
정렬 순서 반전 기능 추가해주실 수 있을까요

### ISSUE THREAD

**Issue by kshman** [hibiyasleep/ikegami#26]
지금 (왼쪽)높은 -> 낮은(오른쪽) 으로 표시되는데
(왼쪽)낮은 <- 높은(오른쪽) 으로 정렬을 반대로 볼 수 있으면 좋겠습니다
![image](https://user-images.githubusercontent.com/7216647/88885680-ebf51180-d273-11ea-83ae-1490145dfb33.png)
Overlay의 Sort는 전혀 먹히지 않더라구요

잘쓰겠습니다. 감사합니다.

**Comment by hibiyasleep** [comment]
이걸 이제야 봤네요 죄송합니다 ... 다음 업데이트 때 추가하도록 할게요!

**Comment by hibiyasleep** [comment]
closed by 6741042444a9ae2d600a8fc1bdd484c833b8d4de
enhanced by 2c1db92e266ff4f98da4d0c1abf575e76f3a045c
다음 업데이트에 (곧) 올라갑니다

![image](https://user-images.githubusercontent.com/5380174/92282400-777b5580-ef38-11ea-949e-85ccdc82b448.png)
