### ISSUE TITLE
No mouseover data

### ISSUE THREAD

**Issue by sparkymotive** [hibiyasleep/ikegami#32]
I have no mouseover data, cannot change settings or interact at all with the overlay beyond moving it.  I made sure that 'Enable Clickthrough' is disabled and even installed a local copy of the overlay.

**Comment by hibiyasleep** [comment]
did you check of overlay total height? Ikegami is only allowed to draw things inside their rectangle, you can check this by enabling `Layout Mode` & expand by dragging right-bottom corner that became draggable by enabling Layout Mode.
