### ISSUE TITLE
Tickers issue and color request

### ISSUE THREAD

**Issue by Hyuinn** [hibiyasleep/ikegami#40]
Critical and Healed Tickers do not appear on top of the bars (the leftmost option, the second one works but that uses some of the default rectangle, which is undesired). Also, is there any way to change the grey/black color of the names not on top DPS to a lighter tone of their role colors?
![issue](https://user-images.githubusercontent.com/46292562/150610388-b6069d7d-80de-4cca-aecf-3f4f54a6929a.png)

**Comment by hibiyasleep** [comment]
1) they're outside of bound of Ikegami has... and seems pretty buggy & hard behavior. since I recommend to put Ikegami at (0, 0)... O<-< I'll try my best tho.
2) so that's because their DPS is too tiny, I'll fix them, as I hid little healing values.
