### ISSUE TITLE
TODO: hide resize handle 

### ISSUE THREAD

**Issue by hibiyasleep** [hibiyasleep/ikegami#5]

**Comment by AlwaysDryzen** [comment]
https://github.com/hibiyasleep/ikegami/blob/c34031abea4494ba9785925c66e54f1dce1af2f4/styles/_index.sass#L27

Changing this from .root.disable-handle::after to .root.hide-handle::after fixes this. It seems like you changed verbage when fixing stuff. Hopefully there isn't another issue blocking this!

**Comment by hibiyasleep** [comment]
oooh just forgot about long times... thanks for reporting!
